---
- hosts: localhost
  remote_user:
  gather_facts: yes

  tasks:
    - name: Run bosboot & bootlist
      bosboot:
        name: run
        bootlist: True
      register: boot_info
      become: true
    - name: get hdisk info
      devices:
        name: disk
      register: disk_info
      become: true
    - name: get fcs info
      devices:
        name: fcs
      register: fcs_info
      become: true
    - name: get ent info
      devices:
        name: ent
      register: ent_info
      become: true
    - name: get etherchannel info
      devices:
        name: port
      register: eth_channel_info
      become: true     
    - name: debug boot
      debug:
        var: boot_info
    - name: debug disk
      debug:
        var: disk_info
    - name: debug disk
      debug:
        var: disk_info
