---
- hosts: all
  remote_user: "{{ lookup('env','USER') }}"
  gather_facts: yes
  
  tasks:
    - name: Run bosboot & bootlist
      bosboot:
         name: run
         bootlist: true
      delegate_to: "127.0.0.1"
      register: result
      become: true

    - name: debug
      debug:
        var: result

