---
- hosts: all
  remote_user: "{{ lookup('env','USER') }}"
  become: true
  become_user: root
  gather_facts: yes
  vars:
     dir_path: /tmp

  tasks:

    - name: "Getting current timestamp"
      set_fact:
         timestamp_fact: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"

    - name: Create directory 
      file:
         path: "{{ dir_path }}/{{ timestamp_fact }}"
         state: directory
         mode: 0755
      delegate_to: "127.0.0.1"

    - name: Create file
      file:
         path: "{{ dir_path }}/{{ timestamp_fact }}/{{ inventory_hostname }}.txt"
         state: touch
         mode: 0755
      delegate_to: "127.0.0.1"

    - name: Mount points
      command: df -k
      register: mnts
      ignore_errors: true

    - name: get hdisk
      aix_list_devices:
        name: disk
      register: disk_info
      become: true
      ignore_errors: true

    - name: get lspv output 
      command: lspv
      register: pvs
      become: true
      ignore_errors: true

    - name: get fcs 
      aix_list_devices:
        name: fcs
      register: fcs_info
      become: true
      ignore_errors: true

    - name: get ent 
      aix_list_devices:
        name: ent
      register: ent_info
      become: true
      ignore_errors: true

    - name: get Path
      command: lspath
      register: paths
      become: true
      ignore_errors: true

    - name: last boot disk
      command: bootinfo -b
      register: lastbootdisk
      become: true
      ignore_errors: true

    - name: get lsvg output
      aix_list_vg:
         name: all
         state: all
      register: lsvg
      become: true
      ignore_errors: true

    - name: get active lsvg output
      aix_list_vg:
         name: all
         state: active
      register: lsvgactive
      become: true
      ignore_errors: true

    - name: Get closed LVs
      aix_list_lv:
        name: all
        state: closed
      register: closedlvs
      ignore_errors: true

    - name: Get stale LVs
      aix_list_lv:
        name: all
        state: stale
      register: stalelvs
      ignore_errors: true

    - name: get ifconfig -a output
      command: ifconfig -a
      register: ifconfig
      become: true
      ignore_errors: true

    - name: get route output
      command: netstat -rn
      register: route
      become: true
      ignore_errors: true

    - name: get etherchannel 
      aix_list_devices:
        name: port
      register: eth_channel_info
      become: true
      ignore_errors: true

    - name: lparstat
      command: lsattr -E -a backup_adapter -l {{ item }}
      register: lparstat
      become: true
      with_items:
            - "{{ eth_channel_info }}"
      ignore_errors: true

    - name: lparstat
      command: lparstat -i
      register: lparstat
      become: true
      ignore_errors: true

    - name: showmount
      command: showmount -a
      register: showmount
      become: true
      ignore_errors: true

    - name: get etherchannel 
      aix_list_devices:
        name: iocp
      register: iocp
      become: true
      ignore_errors: true

    - name: List paging space
      command: lsps -a
      register: paging
      become: true
      ignore_errors: true
      
    - name: Copy the  output to the newly created file
      lineinfile:
        dest:  "{{ dir_path }}/{{ timestamp_fact }}/{{ inventory_hostname }}.txt"
        line: "{{ item.stdout | length}}"
      delegate_to: "127.0.0.1"
      with_items:
        - "mounted filesystems: {{ mnts.stdout_lines|length }}"
        - "Total Disk: {{ disk_info.stdout_lines|length }}"
        - "lspv: {{ pvs.stdout_lines|length }}"
        - "Total fcs: {{ fcs_info.stdout_lines|length }}"
        - "Total ent: {{ ent_info.stdout_lines|length }}"
        - "lspath: {{ paths.stdout_lines|length }}"
        - "Last boot disk: {{ lastbootdisk.stdout_lines|length }}"
        - "Total lsvg: {{ lsvg.stdout_lines|length }}"
        - "Active vg: {{ lsvgactive.stdout_lines|length }}"
        - "Closed lvs: {{ lsvgactive.stdout_lines|length }}"
        - "Stale lvs: {{ lsvgactive.stdout_lines|length }}"
        - "ifconfig details"
        - "{{ ifconfig.stdout_lines }}"
        - "Route details"
        - "{{ route.stdout_lines }}"
        - "Lparstat-i"
        - "{{ lparstat.stdout_lines }}"
        - "Showmount"
        - "{{ showmount.stdout_lines }}" 
        - "icop"
        - "{{ iocp.stdout_lines }}"
        - "paging"
        - "{{ paging.stdout_lines }}"
